version: '3.8'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
  worker-1:
    build: .
    command: celery -A app.celery_config.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
  worker-2:
    build: .
    command: celery -A app.celery_config.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
  
  worker-3:
    build: .
    command: celery -A app.celery_config.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"